openapi: 3.0.3
info:
  title: Projeto controle de pizzas 
  description: |-
   API destinada ao controle de pizzas - SENAI
  termsOfService: http://swagger.io/terms/
  contact:
    email: vertex@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://
paths:
  /v1/senai/pizzaria/pizza:
    post:
      tags:
        - Pizza
      summary: Adiciona uma nova Pizza
      description: Endpoint para enviar os dados da pizza a ser cadastrada
      requestBody:
        description: JSON contendo os dados da nova pizza a ser inserido no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input
        '415':
          description: Invalid Content-Type
        '500':
          description: Error Internal Server (Controller / Model)
    get:
      tags:
        - Pizza
      summary: Lista todas as pizzas
      description: Listagem de todos as pizzas registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'          
           
        '404':
          description: Not Found
        '500':
          description: Error Internal Server (Controller / Model)


  /v1/senai/pizzaria/pizza/{id}:
    get:
      tags:
        - Pizza
      summary: Busca uma pizza pelo ID
      description: Retorna uma pizza pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Pizza
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
        '500':
          description: Error Internal Server (Controller / Model)  
  
    put:
      tags:
        - Pizza
      summary: Atualizar uma Pizza pelo ID
      description: Buscar e atualizar uma Pizza pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Pizza
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma Pizza
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
        '415':
          description: Invalid Content-Type
        '500':
          description: Error Internal Server (Controller / Model)

       
    delete:
      tags:
        - Pizza
      summary: Excluir uma Pizza pelo ID
      description: Buscar e excluir uma Pizza pelo ID
      parameters:
        - name: id
          in: path
          description: ID para buscar a Pizza
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
        '500':
          description: Error Internal Server (Controller / Model)

components:
  schemas:
    Pizza:
      required:
        - descricao
        - imagem
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
        imagem:
          type: string
        sabor:
          type: string
        tipo:
          type: string

  requestBodies:
    Pizza:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pizza'